# Processing Cells for Content Analysis (replaces chunk_processor functionality)

# Multi-format content analysis cell
cell:
  id: "processing:content-analysis"
  description: "Comprehensive content analysis for text, JSON, XML, binary, and image data"
  debug: true

  orchestration:
    startup_timeout: "30s"
    shutdown_timeout: "15s"
    max_retries: 2
    retry_delay: "10s"
    health_check_interval: "30s"

  agents:
    # Text content analysis
    - id: "text-analyzer-001"
      agent_type: "text-analyzer"
      ingress: "sub:content-analysis-text"
      egress: "pub:analyzed-text"
      dependencies: []
      config:
        enable_nlp: false
        enable_sentiment: true
        enable_keywords: true
        max_lines: 10000
        max_keywords: 20

    # JSON content analysis
    - id: "json-analyzer-001"
      agent_type: "json-analyzer"
      ingress: "sub:content-analysis-json"
      egress: "pub:analyzed-json"
      dependencies: []
      config:
        enable_validation: true
        enable_schema_gen: true
        enable_key_analysis: true
        max_depth: 20
        max_keys: 1000
        enable_minification: false

    # XML content analysis
    - id: "xml-analyzer-001"
      agent_type: "xml-analyzer"
      ingress: "sub:content-analysis-xml"
      egress: "pub:analyzed-xml"
      dependencies: []
      config:
        enable_validation: true
        enable_schema_gen: true
        enable_namespace_analysis: true
        max_depth: 20
        max_elements: 1000
        enable_minification: false

    # Binary content analysis
    - id: "binary-analyzer-001"
      agent_type: "binary-analyzer"
      ingress: "sub:content-analysis-binary"
      egress: "pub:analyzed-binary"
      dependencies: []
      config:
        enable_hashing: true
        enable_entropy: true
        enable_magic_bytes: true
        max_analysis_size: 10485760
        enable_structural: true
        enable_compression: false

    # Image content analysis
    - id: "image-analyzer-001"
      agent_type: "image-analyzer"
      ingress: "sub:content-analysis-image"
      egress: "pub:analyzed-image"
      dependencies: []
      config:
        enable_metadata: true
        enable_dimensions: true
        enable_color_analysis: true
        max_analysis_size: 10485760
        enable_thumbnail: false
        enable_quality: true
