# Storage Service Cell
cell:
  id: "service:storage"
  description: "Storage service providing KV, graph, files, and full-text capabilities"
  debug: true

  orchestration:
    startup_timeout: "60s"
    shutdown_timeout: "30s"
    max_retries: 3
    health_check_interval: "30s"

  agents:
    - id: "storage-service-001"
      agent_type: "godast-storage"
      dependencies: []
      # Service mode - no traditional ingress/egress
      config:
        # Storage configuration
        data_path: "/tmp/gox-storage-service"
        max_file_size: 104857600  # 100MB
        enable_kv: true
        enable_graph: true
        enable_files: true
        enable_fulltext: true

        # Service mode configuration
        storage_mode: "service"
        listen_port: 9002
        enable_cors: true
        log_requests: true
        auth_required: false
        max_concurrent_requests: 100
        request_timeout: "30s"

  # Environment variables for service mode
  environment:
    GOX_LOG_LEVEL: "info"
    GOX_STORAGE_MODE: "service"
    GOX_SERVICE_PORT: "9002"
    GOX_METRICS_ENABLED: "true"
