# Specialized JSON/XML analysis cell
cell:
  id: "processing:structured-data-analysis"
  description: "Specialized analysis for structured data formats (JSON, XML)"
  debug: true

  orchestration:
    startup_timeout: "30s"
    shutdown_timeout: "15s"
    max_retries: 2
    retry_delay: "10s"
    health_check_interval: "30s"

  agents:
    # Comprehensive JSON analysis
    - id: "json-analyzer-comprehensive-001"
      agent_type: "json-analyzer"
      ingress: "sub:structured-data-json"
      egress: "pub:comprehensive-analyzed-json"
      dependencies: []
      config:
        enable_validation: true
        enable_schema_gen: true
        enable_key_analysis: true
        max_depth: 50
        max_keys: 10000
        enable_minification: false

    # Comprehensive XML analysis
    - id: "xml-analyzer-comprehensive-001"
      agent_type: "xml-analyzer"
      ingress: "sub:structured-data-xml"
      egress: "pub:comprehensive-analyzed-xml"
      dependencies: []
      config:
        enable_validation: true
        enable_schema_gen: true
        enable_namespace_analysis: true
        max_depth: 50
        max_elements: 10000
        enable_minification: false
