# Text Extraction Cells (native vs. HTTP OCR modes)

# Native text extraction with embedded Tesseract
cell:
  id: "extraction:native-text"
  description: "Text extraction using native Tesseract OCR (no external dependencies)"
  debug: true

  orchestration:
    startup_timeout: "30s"
    shutdown_timeout: "15s"
    max_retries: 2
    retry_delay: "10s"
    health_check_interval: "30s"

  agents:
    - id: "text-extractor-native-001"
      agent_type: "text-extractor-native"
      ingress: "sub:native-text-extraction"
      egress: "pub:extracted-text-native"
      dependencies: []
      config:
        enable_ocr: true
        timeout: 60000000000
        worker_pool_size: 4
        ocr_languages: "eng,deu,fra"
        enable_preprocessing: true
        enable_deskew: true
        enable_noise_removal: true
        contrast_enhancement: true
